config/routes.rb
Cs4720ajk9hyHw3::Application.routes.draw do
  resources :to_do_items

  root :to => 'to_do_items#index'

end

app/models/to_do_item.rb
class ToDoItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
  # GET /to_do_items
  # GET /to_do_items.json
  def index
    @to_do_items = ToDoItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @to_do_items }
    end
  end

  # GET /to_do_items/1
  # GET /to_do_items/1.json
  def show
    @to_do_item = ToDoItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @to_do_item }
    end
  end

  # GET /to_do_items/new
  # GET /to_do_items/new.json
  def new
    @to_do_item = ToDoItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @to_do_item }
    end
  end

  # GET /to_do_items/1/edit
  def edit
    @to_do_item = ToDoItem.find(params[:id])
  end

  # POST /to_do_items
  # POST /to_do_items.json
  def create
    @to_do_item = ToDoItem.new(params[:to_do_item])

    respond_to do |format|
      if @to_do_item.save
        format.html { redirect_to @to_do_item, :notice => 'To do item was successfully created.' }
        format.json { render :json => @to_do_item, :status => :created, :location => @to_do_item }
      else
        format.html { render :action => "new" }
        format.json { render :json => @to_do_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /to_do_items/1
  # PUT /to_do_items/1.json
  def update
    @to_do_item = ToDoItem.find(params[:id])

    respond_to do |format|
      if @to_do_item.update_attributes(params[:to_do_item])
        format.html { redirect_to @to_do_item, :notice => 'To do item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @to_do_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /to_do_items/1
  # DELETE /to_do_items/1.json
  def destroy
    @to_do_item = ToDoItem.find(params[:id])
    @to_do_item.destroy

    respond_to do |format|
      format.html { redirect_to to_do_items_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework 3 - Rails Demo</title>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<h1 class="main"><span>Ruby Demo</span></h1>
	<div class="wrapper">
		<%= yield %>
	</div>
	<div class="bottom">
		<%= link_to 'Add To-Do Item', new_to_do_item_path, :class => "add sub bottom", :id => "add"  %>
	</div>
</div>
</body>
</html>

app/views/to_do_items/_form.html.erb
<%= form_for(@to_do_item) do |f| %>
  <% if @to_do_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@to_do_item.errors.count, "error") %> prohibited this to_do_item from being saved:</h2>

      <ul>
      <% @to_do_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Item %><br />
    <%= f.text_field :Item %>
  </div>
  <div class="field">
    <%= f.label :DueDate %><br />
    <%= f.date_select :DueDate %>
  </div>
  <div class="field">
    <%= f.label :Completed %><br />
    <%= f.check_box :Completed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/to_do_items/edit.html.erb
<h2>Editing Item: <strong><%= @to_do_item.Item %></strong></h2>

<%= render 'form' %>

<%= link_to 'Show', @to_do_item %> |
<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/index.html.erb
<h2>To-Do List</h2>
<!--
<table>
	<tr>
    	<th>Item</th>
    	<th>Duedate</th>
    	<th>Completed</th>
	    <th></th>
	    <th></th>
	    <th></th>
	</tr>
-->
<!-- 
<% @to_do_items.each do |to_do_item| %>
  <tr>
    <td><%= to_do_item.Item %></td>
    <td><%= to_do_item.DueDate %></td>
    <td><%= to_do_item.Completed %></td>
    <td><%= link_to 'Show', to_do_item %></td>
    <td><%= link_to 'Edit', edit_to_do_item_path(to_do_item) %></td>
    <td><%= link_to 'Destroy', to_do_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  </table>
<% end %>
-->
<ul>
<% @to_do_items.each do |to_do_item| %>
	<li><%= link_to to_do_item.Item, to_do_item, :class => "item" %>
		<div>
		<%= link_to 'Edit', edit_to_do_item_path(to_do_item), :class => "edit sub" %>
		<%= link_to 'Destroy', to_do_item, :method => :delete, :class => "delete sub" %>
		</div>
	</li>
<% end %>
</ul>

app/views/to_do_items/new.html.erb
<h2>Create To-Do Item</h2>

<%= render 'form' %>

<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/show.html.erb
<h2>About Item: <strong><%= @to_do_item.Item %></strong></h2>
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @to_do_item.Item %>
</p>

<p>
  <b>Duedate:</b>
  <%= @to_do_item.DueDate %>
</p>

<p>
  <b>Completed:</b>
  <%= @to_do_item.Completed %>
</p>


<%= link_to 'Edit', edit_to_do_item_path(@to_do_item) %> |
<%= link_to 'Back', to_do_items_path %>